First last page
mohitkyadav/react-pagination-nav pull request #12
Opened 2020-10-01 20:18 UTC by aelamel

Related to #5

2020-10-03 03:52 UTC, mohitkyadav requested changes

2020-10-03 03:52 UTC, mohitkyadav commented on src/ReactPaginationNav.js
> +          onClick={() => goToFirstPage()}
add it to prop types and double check
`goToFirstPage && goToFirstPage()`

2020-10-03 03:52 UTC, mohitkyadav commented on src/ReactPaginationNav.js
> +          onClick={() => goToLastPage()}
add it to prop types and double check
`goToLastPage && goToLastPage()`

2020-10-03 11:32 UTC, aelamel commented on src/ReactPaginationNav.js
> +          onClick={() => goToFirstPage()}
Done

2020-10-03 11:34 UTC, aelamel reviewed
Changes have been made

2020-10-04 07:44 UTC, mohitkyadav approved these changes

2020-10-04 07:44 UTC, mohitkyadav commented
please resolve conflicts @aelamel

2020-10-05 04:54 UTC, mohitkyadav approved these changes
conflicts @aelamel and LGTM

2020-10-05 13:06 UTC, villa7 commented on src/ReactPaginationNav.js
> +  PageButton,
Duplicate prop PageButton

```suggestion
```

2020-10-05 13:06 UTC, villa7 commented on src/ReactPaginationNav.js
> +      {!isPreviousBtnHidden && (
Previous button should be handled by PrevNextButton prop, remove duplicate

2020-10-05 13:07 UTC, villa7 commented on src/ReactPaginationNav.js
> +              <button
handled by PageButton prop, remove duplicate

2020-10-05 13:09 UTC, villa7 commented on src/ReactPaginationNav.js
> +      {!isNextBtnHidden && (
handled by PrevNextButton prop, remove duplicate and move lastBtn after the nextBtn

2020-10-05 13:45 UTC, aelamel commented
Fixed in #18

2020-10-06 03:31 UTC, merged